import json
from cv2.dnn import readNetFromTensorflow


# Application system settings

with open("settings.json", "r") as f:
    SETTINGS = json.load(f)

# Application metadata

with open("info.json", "r") as f:
    INFO = json.load(f)

# Application description

with open("description.md", "r") as f:
    DESCRIPTION = f.read()

# Tempdir for saving images
# (saved on the machine's filesystem, usually in /var/lib/docker)
# Do not change!

TEMP_DIR = "/tmp"


# Load the MobileNet SSD model trained on the COCO dataset

NET = readNetFromTensorflow(
    "ssd_mobilenet/frozen_inference_graph.pb",
    "ssd_mobilenet/ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt",
)

GOOGLE_VISION_URL = "https://vision.googleapis.com/v1/images:annotate?key="

# Load the class labels the object model was trained on

COCO_LABELS = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "street sign",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "hat",
    "backpack",
    "umbrella",
    "shoe",
    "eye glasses",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "plate",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "mirror",
    "dining table",
    "window",
    "desk",
    "toilet",
    "door",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "blender",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]

COCO_2_WIKIDATA = {
    "airplane": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q197",
        "wikidata_label": "airplane",
        "wikidata_description": "powered fixed-wing aircraft",
        "wikidata_concept": "Q197",
    },
    "apple": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q89",
        "wikidata_label": "apple",
        "wikidata_description": "fruit of the apple tree",
        "wikidata_concept": "Q89",
    },
    "backpack": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q5843",
        "wikidata_label": "backpack",
        "wikidata_description": "bag carried on one's back",
        "wikidata_concept": "Q5843",
    },
    "banana": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q503",
        "wikidata_label": "banana",
        "wikidata_description": "elongated, edible fruit produced by several kinds of large herbaceous flowering plants in the genus Musa",
        "wikidata_concept": "Q503",
    },
    "baseball bat": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q809910",
        "wikidata_label": "baseball bat",
        "wikidata_description": "club used for baseball, or as a weapon",
        "wikidata_concept": "Q809910",
    },
    "baseball glove": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q809894",
        "wikidata_label": "baseball glove",
        "wikidata_description": "large leather glove worn by baseball players",
        "wikidata_concept": "Q809894",
    },
    "bear": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q30090244",
        "wikidata_label": "bear",
        "wikidata_description": "large carnivoran mammal of the family Ursidae",
        "wikidata_concept": "Q30090244",
    },
    "bed": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q42177",
        "wikidata_label": "bed",
        "wikidata_description": "piece of furniture used as a place to sleep or relax",
        "wikidata_concept": "Q42177",
    },
    "bench": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q204776",
        "wikidata_label": "bench",
        "wikidata_description": "piece of furniture on which several people may sit at the same time",
        "wikidata_concept": "Q204776",
    },
    "bicycle": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q11442",
        "wikidata_label": "bicycle",
        "wikidata_description": "pedal-driven two-wheel vehicle",
        "wikidata_concept": "Q11442",
    },
    "bird": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q5113",
        "wikidata_label": "bird",
        "wikidata_description": "class of vertebrates",
        "wikidata_concept": "Q5113",
    },
    "blender": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q501862",
        "wikidata_label": "blender",
        "wikidata_description": "type of home appliance",
        "wikidata_concept": "Q501862",
    },
    "boat": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q35872",
        "wikidata_label": "boat",
        "wikidata_description": "smaller watercraft",
        "wikidata_concept": "Q35872",
    },
    "book": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q571",
        "wikidata_label": "book",
        "wikidata_description": "medium for recording information (words or images) typically on bound pages or more abstractly in electronic or audio form",
        "wikidata_concept": "Q571",
    },
    "bottle": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q80228",
        "wikidata_label": "bottle",
        "wikidata_description": "cylindrical container",
        "wikidata_concept": "Q80228",
    },
    "bowl": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q153988",
        "wikidata_label": "bowl",
        "wikidata_description": "round, open-top container frequently used as tableware",
        "wikidata_concept": "Q153988",
    },
    "broccoli": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q47722",
        "wikidata_label": "broccoli",
        "wikidata_description": "edible green plant in the cabbage family",
        "wikidata_concept": "Q47722",
    },
    "bus": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q5638",
        "wikidata_label": "bus",
        "wikidata_description": "large road vehicle for transporting people",
        "wikidata_concept": "Q5638",
    },
    "cake": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q13276",
        "wikidata_label": "cake",
        "wikidata_description": "baked dessert",
        "wikidata_concept": "Q13276",
    },
    "car": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q1420",
        "wikidata_label": "motor car",
        "wikidata_description": "motorized road vehicle designed to carry one to eight people rather than primarily goods",
        "wikidata_concept": "Q1420",
    },
    "carrot": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q81",
        "wikidata_label": "carrot",
        "wikidata_description": "root vegetable, usually orange in color",
        "wikidata_concept": "Q81",
    },
    "cat": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q146",
        "wikidata_label": "house cat",
        "wikidata_description": "domesticated feline",
        "wikidata_concept": "Q146",
    },
    "chair": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q15026",
        "wikidata_label": "chair",
        "wikidata_description": "piece of furniture for sitting on",
        "wikidata_concept": "Q15026",
    },
    "clock": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q376",
        "wikidata_label": "clock",
        "wikidata_description": "instrument that measures the passage of time",
        "wikidata_concept": "Q376",
    },
    "couch": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q131514",
        "wikidata_label": "couch",
        "wikidata_description": "piece of furniture for seating two or more persons in the form of a bench with armrests",
        "wikidata_concept": "Q131514",
    },
    "cow": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q11748378",
        "wikidata_label": "cow",
        "wikidata_description": "adult female cattle",
        "wikidata_concept": "Q11748378",
    },
    "cup": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q81727",
        "wikidata_label": "cup",
        "wikidata_description": "vessel for liquids",
        "wikidata_concept": "Q81727",
    },
    "desk": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q1064858",
        "wikidata_label": "desk",
        "wikidata_description": "case furniture used as a worksurface, often in a school or office setting",
        "wikidata_concept": "Q1064858",
    },
    "dining table": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q115665141",
        "wikidata_label": "dining table",
        "wikidata_description": "table for dining, usually for formal meals",
        "wikidata_concept": "Q115665141",
    },
    "dog": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q144",
        "wikidata_label": "dog",
        "wikidata_description": "domestic animal",
        "wikidata_concept": "Q144",
    },
    "door": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q36794",
        "wikidata_label": "door",
        "wikidata_description": "flat, movable structure used to open and close an entrance",
        "wikidata_concept": "Q36794",
    },
    "elephant": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q7378",
        "wikidata_label": "elephant",
        "wikidata_description": "large terrestrial mammals with trunks from Africa and Asia",
        "wikidata_concept": "Q7378",
    },
    "fire hydrant": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q634299",
        "wikidata_label": "fire hydrant",
        "wikidata_description": "connection point by which firefighters can tap into a water supply",
        "wikidata_concept": "Q634299",
    },
    "fork": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q81881",
        "wikidata_label": "fork",
        "wikidata_description": "utensil to spear food",
        "wikidata_concept": "Q81881",
    },
    "giraffe": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q15083",
        "wikidata_label": "giraffe",
        "wikidata_description": "umbrella species of Giraffa",
        "wikidata_concept": "Q15083",
    },
    "handbag": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q467505",
        "wikidata_label": "handbag",
        "wikidata_description": "handled medium-to-large bag that is often fashionably designed, typically used by women, to hold personal items",
        "wikidata_concept": "Q467505",
    },
    "hat": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q80151",
        "wikidata_label": "hat",
        "wikidata_description": "shaped head covering, having a brim and a crown, or one of these",
        "wikidata_concept": "Q80151",
    },
    "horse": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q726",
        "wikidata_label": "horse",
        "wikidata_description": "domesticated four-footed mammal from the equine family",
        "wikidata_concept": "Q726",
    },
    "hot dog": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q181055",
        "wikidata_label": "hot dog",
        "wikidata_description": "sausage in bun, usually with toppings",
        "wikidata_concept": "Q181055",
    },
    "keyboard": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q1921606",
        "wikidata_label": "keyboard",
        "wikidata_description": "data input device",
        "wikidata_concept": "Q1921606",
    },
    "kite": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q42861",
        "wikidata_label": "kite",
        "wikidata_description": "tethered aircraft often tied with a rope or string.",
        "wikidata_concept": "Q42861",
    },
    "knife": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q32489",
        "wikidata_label": "knife",
        "wikidata_description": "tool with a cutting edge or blade",
        "wikidata_concept": "Q32489",
    },
    "laptop": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q3962",
        "wikidata_label": "laptop",
        "wikidata_description": "foldable portable personal computer for mobile use",
        "wikidata_concept": "Q3962",
    },
    "microwave": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q127956",
        "wikidata_label": "microwave oven",
        "wikidata_description": "kitchen cooking appliance",
        "wikidata_concept": "Q127956",
    },
    "mirror": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q146701",
        "wikidata_label": "mirror",
        "wikidata_description": "transparent structure in the eye",
        "wikidata_concept": "Q146701",
    },
    "motorcycle": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q34493",
        "wikidata_label": "motorcycle",
        "wikidata_description": "two- or three-wheeled motor vehicle",
        "wikidata_concept": "Q34493",
    },
    "mouse": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q7987",
        "wikidata_label": "mouse",
        "wikidata_description": "hand-held device used to move a pointer on a computer display",
        "wikidata_concept": "Q7987",
    },
    "orange": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q13191",
        "wikidata_label": "orange",
        "wikidata_description": "citrus fruit of the orange tree",
        "wikidata_concept": "Q13191",
    },
    "oven": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q36539",
        "wikidata_label": "oven",
        "wikidata_description": "enclosed chamber for heating other objects, often used to prepare food, finish ceramics, and purify substances",
        "wikidata_concept": "Q36539",
    },
    "parking meter": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q953960",
        "wikidata_label": "parking meter",
        "wikidata_description": "device",
        "wikidata_concept": "Q953960",
    },
    "person": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q215627",
        "wikidata_label": "person",
        "wikidata_description": "being that has certain capacities or attributes constituting personhood (avoid use with P31; use Q5 for humans)",
        "wikidata_concept": "Q215627",
    },
    "pizza": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q177",
        "wikidata_label": "pizza",
        "wikidata_description": "popular Italian dish with a flat dough-based base and toppings",
        "wikidata_concept": "Q177",
    },
    "plate": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q57216",
        "wikidata_label": "plate",
        "wikidata_description": "flat vessel on which food can be served",
        "wikidata_concept": "Q57216",
    },
    "potted plant": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q27993793",
        "wikidata_label": "potted plant",
        "wikidata_description": "plant grown in a container",
        "wikidata_concept": "Q27993793",
    },
    "refrigerator": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q37828",
        "wikidata_label": "refrigerator",
        "wikidata_description": "household or industrial appliance for preserving food at a low temperature",
        "wikidata_concept": "Q37828",
    },
    "remote": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q185091",
        "wikidata_label": "remote control",
        "wikidata_description": "system or device used to control other device remotely (or wirelessly)",
        "wikidata_concept": "Q185091",
    },
    "sandwich": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q28803",
        "wikidata_label": "sandwich",
        "wikidata_description": "any dish wherein bread serves as a container or wrapper for another food type; not to be confused with Q111836983 (the narrower sense of 'sandwich')",
        "wikidata_concept": "Q28803",
    },
    "scissors": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q40847",
        "wikidata_label": "scissors",
        "wikidata_description": "hand-operated cutting instrument",
        "wikidata_concept": "Q40847",
    },
    "sheep": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q7368",
        "wikidata_label": "sheep",
        "wikidata_description": "domesticated ruminant bred for meat, wool, and milk",
        "wikidata_concept": "Q7368",
    },
    "shoe": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q22676",
        "wikidata_label": "shoe",
        "wikidata_description": "footwear",
        "wikidata_concept": "Q22676",
    },
    "sink": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q140565",
        "wikidata_label": "sink",
        "wikidata_description": "bowl-shaped plumbing fixture used for washing hands",
        "wikidata_concept": "Q140565",
    },
    "skateboard": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q15783",
        "wikidata_label": "skateboard",
        "wikidata_description": "wheeled board used for skateboarding",
        "wikidata_concept": "Q15783",
    },
    "snowboard": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q2000617",
        "wikidata_label": "snowboard",
        "wikidata_description": "winter sport equipment",
        "wikidata_concept": "Q2000617",
    },
    "spoon": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q81895",
        "wikidata_label": "spoon",
        "wikidata_description": "utensil consisting of a small shallow bowl, oval or round, at the end of a handle",
        "wikidata_concept": "Q81895",
    },
    "stop sign": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q250429",
        "wikidata_label": "stop sign",
        "wikidata_description": "A sign representing a temporary stop traffic regulation",
        "wikidata_concept": "Q250429",
    },
    "suitcase": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q200814",
        "wikidata_label": "suitcase",
        "wikidata_description": "form of luggage",
        "wikidata_concept": "Q200814",
    },
    "surfboard": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q457689",
        "wikidata_label": "surfboard",
        "wikidata_description": "platform board used in the sport of surfing",
        "wikidata_concept": "Q457689",
    },
    "teddy bear": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q213477",
        "wikidata_label": "teddy bear",
        "wikidata_description": "soft toy in the form of a bear",
        "wikidata_concept": "Q213477",
    },
    "tie": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q44416",
        "wikidata_label": "necktie",
        "wikidata_description": "clothing item, traditionally worn by boys and men with dress shirt",
        "wikidata_concept": "Q44416",
    },
    "toaster": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q14890",
        "wikidata_label": "toaster",
        "wikidata_description": "small oven for cooking bread",
        "wikidata_concept": "Q14890",
    },
    "toilet": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q7857",
        "wikidata_label": "toilet",
        "wikidata_description": "sanitation fixture",
        "wikidata_concept": "Q7857",
    },
    "toothbrush": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q134205",
        "wikidata_label": "toothbrush",
        "wikidata_description": "oral hygiene instrument used to clean the teeth, gums, and tongue",
        "wikidata_concept": "Q134205",
    },
    "traffic light": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q8004",
        "wikidata_label": "traffic light",
        "wikidata_description": "signalling device to control competing flows of traffic",
        "wikidata_concept": "Q8004",
    },
    "train": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q870",
        "wikidata_label": "train",
        "wikidata_description": "form of rail transport consisting of a series of connected vehicles",
        "wikidata_concept": "Q870",
    },
    "truck": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q43193",
        "wikidata_label": "truck",
        "wikidata_description": "commercial or utilitarian large motor vehicle",
        "wikidata_concept": "Q43193",
    },
    "umbrella": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q41607",
        "wikidata_label": "umbrella",
        "wikidata_description": "canopy designed to protect against rain or sun",
        "wikidata_concept": "Q41607",
    },
    "vase": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q191851",
        "wikidata_label": "vase",
        "wikidata_description": "open container, often used to hold cut flowers",
        "wikidata_concept": "Q191851",
    },
    "window": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q35473",
        "wikidata_label": "window",
        "wikidata_description": "opening to admit light or air",
        "wikidata_concept": "Q35473",
    },
    "wine glass": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q1531435",
        "wikidata_label": "wine glass",
        "wikidata_description": "drinking vessel",
        "wikidata_concept": "Q1531435",
    },
    "zebra": {
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q32789",
        "wikidata_label": "zebra",
        "wikidata_description": "Group of African mammal species in the genus Equus of the horse family",
        "wikidata_concept": "Q32789",
    },
}

EFT_IDS = {
    "orange": {
        "wikidata_concept": "Q39338",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q39338",
        "europeana_concept": "10411",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10411",
    },
    "black": {
        "wikidata_concept": "Q23445",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q23445",
        "europeana_concept": "10401",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10401",
    },
    "purple": {
        "wikidata_concept": "Q3257809",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q3257809",
        "europeana_concept": "10413",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10413",
    },
    "red": {
        "wikidata_concept": "Q3142",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q3142",
        "europeana_concept": "10414",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10414",
    },
    "grey": {
        "wikidata_concept": "Q42519",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q42519",
        "europeana_concept": "10405",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10405",
    },
    "gold": {
        "wikidata_concept": "Q208045",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q208045",
        "europeana_concept": "10406",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10406",
    },
    "copper": {
        "wikidata_concept": "Q2722041",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q2722041",
        "europeana_concept": "10409",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10409",
    },
    "yellow": {
        "wikidata_concept": "Q943",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q943",
        "europeana_concept": "10417",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10417",
    },
    "green": {
        "wikidata_concept": "Q3133",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q3133",
        "europeana_concept": "10404",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10404",
    },
    "brown": {
        "wikidata_concept": "Q47071",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q47071",
        "europeana_concept": "10403",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10403",
    },
    "blue": {
        "wikidata_concept": "Q1088",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q1088",
        "europeana_concept": "10402",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10402",
    },
    "white": {
        "wikidata_concept": "Q23444",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q23444",
        "europeana_concept": "10416",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10416",
    },
    "beige": {
        "wikidata_concept": "Q843607",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q843607",
        "europeana_concept": "10778",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10778",
    },
    "pink": {
        "wikidata_concept": "Q429220",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q429220",
        "europeana_concept": "10412",
        "europeana_concepturi": "http://thesaurus.europeanafashion.eu/thesaurus/10412",
    },
}

EFT_COLORS = [
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 255,
        "G": 228,
        "B": 196,
    },
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 245,
        "G": 245,
        "B": 220,
    },
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 255,
        "G": 235,
        "B": 205,
    },
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 222,
        "G": 184,
        "B": 135,
    },
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 255,
        "G": 222,
        "B": 173,
    },
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 255,
        "G": 228,
        "B": 181,
    },
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 210,
        "G": 180,
        "B": 140,
    },
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 255,
        "G": 239,
        "B": 213,
    },
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 255,
        "G": 248,
        "B": 220,
    },
    {
        "color": "Beige",
        "color_name": "Beige",
        "R": 245,
        "G": 222,
        "B": 179,
    },
    {
        "color": "Black",
        "color_name": "Black",
        "R": 0,
        "G": 0,
        "B": 0,
    },
    {
        "color": "Black",
        "color_name": "Black",
        "R": 30,
        "G": 30,
        "B": 30,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 119,
        "G": 136,
        "B": 153,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 25,
        "G": 25,
        "B": 112,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 135,
        "G": 206,
        "B": 235,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 65,
        "G": 105,
        "B": 225,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 0,
        "G": 0,
        "B": 128,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 173,
        "G": 216,
        "B": 230,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 176,
        "G": 196,
        "B": 222,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 30,
        "G": 144,
        "B": 255,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 0,
        "G": 0,
        "B": 255,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 100,
        "G": 149,
        "B": 237,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 0,
        "G": 191,
        "B": 255,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 70,
        "G": 130,
        "B": 180,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 0,
        "G": 0,
        "B": 139,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 135,
        "G": 206,
        "B": 250,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 0,
        "G": 0,
        "B": 205,
    },
    {
        "color": "Blue",
        "color_name": "Blue",
        "R": 240,
        "G": 248,
        "B": 255,
    },
    {
        "color": "Pink",
        "color_name": "Beige",
        "R": 188,
        "G": 143,
        "B": 143,
    },
    {
        "color": "Brown",
        "color_name": "Brown",
        "R": 205,
        "G": 133,
        "B": 63,
    },
    {
        "color": "Brown",
        "color_name": "Brown",
        "R": 160,
        "G": 82,
        "B": 45,
    },
    {
        "color": "Brown",
        "color_name": "Brown",
        "R": 128,
        "G": 0,
        "B": 0,
    },
    {
        "color": "Brown",
        "color_name": "Brown",
        "R": 139,
        "G": 69,
        "B": 19,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 0,
        "G": 139,
        "B": 139,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 60,
        "G": 179,
        "B": 113,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 0,
        "G": 255,
        "B": 255,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 95,
        "G": 158,
        "B": 160,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 175,
        "G": 238,
        "B": 238,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 176,
        "G": 224,
        "B": 230,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 224,
        "G": 255,
        "B": 255,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 0,
        "G": 128,
        "B": 128,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 32,
        "G": 178,
        "B": 170,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 64,
        "G": 224,
        "B": 208,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 0,
        "G": 206,
        "B": 209,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 102,
        "G": 205,
        "B": 170,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 0,
        "G": 250,
        "B": 154,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 127,
        "G": 255,
        "B": 212,
    },
    {
        "color": "Cyan",
        "color_name": "Cyan",
        "R": 72,
        "G": 209,
        "B": 204,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 144,
        "G": 238,
        "B": 144,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 0,
        "G": 255,
        "B": 127,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 50,
        "G": 205,
        "B": 50,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 152,
        "G": 251,
        "B": 152,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 0,
        "G": 255,
        "B": 0,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 0,
        "G": 128,
        "B": 0,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 46,
        "G": 139,
        "B": 87,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 154,
        "G": 205,
        "B": 50,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 143,
        "G": 188,
        "B": 143,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 127,
        "G": 255,
        "B": 0,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 107,
        "G": 142,
        "B": 35,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 124,
        "G": 252,
        "B": 0,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 0,
        "G": 100,
        "B": 0,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 173,
        "G": 255,
        "B": 47,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 85,
        "G": 107,
        "B": 47,
    },
    {
        "color": "Green",
        "color_name": "Green",
        "R": 34,
        "G": 139,
        "B": 34,
    },
    {
        "color": "Grey",
        "color_name": "Grey",
        "R": 169,
        "G": 169,
        "B": 169,
    },
    {
        "color": "Grey",
        "color_name": "Grey",
        "R": 128,
        "G": 128,
        "B": 128,
    },
    {
        "color": "Grey",
        "color_name": "Grey",
        "R": 105,
        "G": 105,
        "B": 105,
    },
    {
        "color": "Grey",
        "color_name": "Grey",
        "R": 192,
        "G": 192,
        "B": 192,
    },
    {
        "color": "Grey",
        "color_name": "Grey",
        "R": 211,
        "G": 211,
        "B": 211,
    },
    {
        "color": "Grey",
        "color_name": "Grey",
        "R": 47,
        "G": 79,
        "B": 79,
    },
    {
        "color": "Grey",
        "color_name": "Grey",
        "R": 112,
        "G": 128,
        "B": 144,
    },
    {
        "color": "Olive",
        "color_name": "Olive",
        "R": 128,
        "G": 128,
        "B": 0,
    },
    {
        "color": "Olive",
        "color_name": "Olive",
        "R": 189,
        "G": 183,
        "B": 107,
    },
    {
        "color": "Orange",
        "color_name": "Orange",
        "R": 244,
        "G": 164,
        "B": 96,
    },
    {
        "color": "Orange",
        "color_name": "Orange",
        "R": 255,
        "G": 165,
        "B": 0,
    },
    {
        "color": "Orange",
        "color_name": "Orange",
        "R": 255,
        "G": 99,
        "B": 71,
    },
    {
        "color": "Orange",
        "color_name": "Orange",
        "R": 255,
        "G": 140,
        "B": 0,
    },
    {
        "color": "Orange",
        "color_name": "Orange",
        "R": 255,
        "G": 127,
        "B": 80,
    },
    {
        "color": "Orange",
        "color_name": "Orange",
        "R": 210,
        "G": 105,
        "B": 30,
    },
    {
        "color": "Orange",
        "color_name": "Orange",
        "R": 255,
        "G": 69,
        "B": 0,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 190,
        "G": 130,
        "B": 170,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 255,
        "G": 0,
        "B": 255,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 255,
        "G": 182,
        "B": 193,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 240,
        "G": 128,
        "B": 128,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 221,
        "G": 160,
        "B": 221,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 255,
        "G": 192,
        "B": 203,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 255,
        "G": 105,
        "B": 180,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 255,
        "G": 228,
        "B": 225,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 238,
        "G": 130,
        "B": 238,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 219,
        "G": 112,
        "B": 147,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 199,
        "G": 21,
        "B": 133,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 255,
        "G": 160,
        "B": 122,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 250,
        "G": 128,
        "B": 114,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 218,
        "G": 112,
        "B": 214,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 255,
        "G": 20,
        "B": 147,
    },
    {
        "color": "Pink",
        "color_name": "Pink",
        "R": 255,
        "G": 218,
        "B": 185,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 153,
        "G": 50,
        "B": 204,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 75,
        "G": 0,
        "B": 130,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 230,
        "G": 230,
        "B": 250,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 186,
        "G": 85,
        "B": 211,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 106,
        "G": 90,
        "B": 205,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 123,
        "G": 104,
        "B": 238,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 138,
        "G": 43,
        "B": 226,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 147,
        "G": 112,
        "B": 219,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 139,
        "G": 0,
        "B": 139,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 128,
        "G": 0,
        "B": 128,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 72,
        "G": 61,
        "B": 139,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 148,
        "G": 0,
        "B": 211,
    },
    {
        "color": "Purple",
        "color_name": "Purple",
        "R": 216,
        "G": 191,
        "B": 216,
    },
    {
        "color": "Red",
        "color_name": "Red",
        "R": 233,
        "G": 150,
        "B": 122,
    },
    {
        "color": "Red",
        "color_name": "Red",
        "R": 205,
        "G": 92,
        "B": 92,
    },
    {
        "color": "Red",
        "color_name": "Red",
        "R": 255,
        "G": 0,
        "B": 0,
    },
    {
        "color": "Red",
        "color_name": "Red",
        "R": 178,
        "G": 34,
        "B": 34,
    },
    {
        "color": "Red",
        "color_name": "Red",
        "R": 165,
        "G": 42,
        "B": 42,
    },
    {
        "color": "Red",
        "color_name": "Red",
        "R": 139,
        "G": 0,
        "B": 0,
    },
    {
        "color": "Red",
        "color_name": "Red",
        "R": 220,
        "G": 20,
        "B": 60,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 240,
        "G": 255,
        "B": 255,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 250,
        "G": 235,
        "B": 215,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 255,
        "G": 250,
        "B": 240,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 255,
        "G": 250,
        "B": 250,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 220,
        "G": 220,
        "B": 220,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 255,
        "G": 255,
        "B": 255,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 255,
        "G": 255,
        "B": 240,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 240,
        "G": 255,
        "B": 240,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 250,
        "G": 240,
        "B": 230,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 255,
        "G": 240,
        "B": 245,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 248,
        "G": 248,
        "B": 255,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 245,
        "G": 245,
        "B": 245,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 255,
        "G": 245,
        "B": 238,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 253,
        "G": 245,
        "B": 230,
    },
    {
        "color": "White",
        "color_name": "White",
        "R": 245,
        "G": 255,
        "B": 250,
    },
    {
        "color": "Yellow",
        "color_name": "Yellow",
        "R": 250,
        "G": 250,
        "B": 210,
    },
    {
        "color": "Yellow",
        "color_name": "Yellow",
        "R": 255,
        "G": 255,
        "B": 0,
    },
    {
        "color": "Yellow",
        "color_name": "Yellow",
        "R": 240,
        "G": 230,
        "B": 140,
    },
    {
        "color": "Yellow",
        "color_name": "Yellow",
        "R": 255,
        "G": 255,
        "B": 224,
    },
    {
        "color": "Yellow",
        "color_name": "Yellow",
        "R": 218,
        "G": 165,
        "B": 32,
    },
    {
        "color": "Yellow",
        "color_name": "Yellow",
        "R": 255,
        "G": 215,
        "B": 0,
    },
    {
        "color": "Yellow",
        "color_name": "Yellow",
        "R": 255,
        "G": 250,
        "B": 205,
    },
    {
        "color": "Yellow",
        "color_name": "Yellow",
        "R": 238,
        "G": 232,
        "B": 170,
    },
]
