EFT_COLORS = [
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#00308f",
        "R": 255,
        "G": 228,
        "B": 196,
        "RGB": "(255,228,196)",
        "note": "",
    },
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#5d8aa8",
        "R": 245,
        "G": 245,
        "B": 220,
        "RGB": "(245,245,220)",
        "note": "",
    },
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#72a0c1",
        "R": 255,
        "G": 235,
        "B": 205,
        "RGB": "(255,235,205)",
        "note": "",
    },
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#a32638",
        "R": 222,
        "G": 184,
        "B": 135,
        "RGB": "(222,184,135)",
        "note": "",
    },
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#c46210",
        "R": 255,
        "G": 222,
        "B": 173,
        "RGB": "(255,222,173)",
        "note": "",
    },
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#e32636",
        "R": 255,
        "G": 228,
        "B": 181,
        "RGB": "(255,228,181)",
        "note": "",
    },
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#e52b50",
        "R": 210,
        "G": 180,
        "B": 140,
        "RGB": "(210,180,140)",
        "note": "",
    },
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#efdecd",
        "R": 255,
        "G": 239,
        "B": 213,
        "RGB": "(255,239,213)",
        "note": "",
    },
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#f0f8ff",
        "R": 255,
        "G": 248,
        "B": 220,
        "RGB": "(255,248,220)",
        "note": "",
    },
    {
        "color": "beige",
        "color_name": "beige",
        "hex": "#ffbf00",
        "R": 245,
        "G": 222,
        "B": 179,
        "RGB": "(245,222,179)",
        "note": "",
    },
    {
        "color": "black",
        "color_name": "black",
        "hex": "#ff7e00",
        "R": 0,
        "G": 0,
        "B": 0,
        "RGB": "(0,0,0)",
        "note": "",
    },
    {
        "color": "black",
        "color_name": "black",
        "hex": "#1e1e1e",
        "R": 30,
        "G": 30,
        "B": 30,
        "RGB": "(30,30,30)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#008000",
        "R": 119,
        "G": 136,
        "B": 153,
        "RGB": "(119,136,153)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#0ff",
        "R": 25,
        "G": 25,
        "B": 112,
        "RGB": "(25,25,112)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#3b444b",
        "R": 135,
        "G": 206,
        "B": 235,
        "RGB": "(135,206,235)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#4b5320",
        "R": 65,
        "G": 105,
        "B": 225,
        "RGB": "(65,105,225)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#7fffd4",
        "R": 0,
        "G": 0,
        "B": 128,
        "RGB": "(0,0,128)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#841b2d",
        "R": 173,
        "G": 216,
        "B": 230,
        "RGB": "(173,216,230)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#8db600",
        "R": 176,
        "G": 196,
        "B": 222,
        "RGB": "(176,196,222)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#915c83",
        "R": 30,
        "G": 144,
        "B": 255,
        "RGB": "(30,144,255)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#96c",
        "R": 0,
        "G": 0,
        "B": 255,
        "RGB": "(0,0,255)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#a4c639",
        "R": 100,
        "G": 149,
        "B": 237,
        "RGB": "(100,149,237)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#cd9575",
        "R": 0,
        "G": 191,
        "B": 255,
        "RGB": "(0,191,255)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#e9d66b",
        "R": 70,
        "G": 130,
        "B": 180,
        "RGB": "(70,130,180)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#f2f3f4",
        "R": 0,
        "G": 0,
        "B": 139,
        "RGB": "(0,0,139)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#faebd7",
        "R": 135,
        "G": 206,
        "B": 250,
        "RGB": "(135,206,250)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#fbceb1",
        "R": 0,
        "G": 0,
        "B": 205,
        "RGB": "(0,0,205)",
        "note": "",
    },
    {
        "color": "blue",
        "color_name": "blue",
        "hex": "#ff033e",
        "R": 240,
        "G": 248,
        "B": 255,
        "RGB": "(240,248,255)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "beige",
        "hex": "#007fff",
        "R": 188,
        "G": 143,
        "B": 143,
        "RGB": "(188,143,143)",
        "note": "changed to pink",
    },
    {
        "color": "brown",
        "color_name": "brown",
        "hex": "#87a96b",
        "R": 205,
        "G": 133,
        "B": 63,
        "RGB": "(205,133,63)",
        "note": "",
    },
    {
        "color": "brown",
        "color_name": "brown",
        "hex": "#a52a2a",
        "R": 160,
        "G": 82,
        "B": 45,
        "RGB": "(160,82,45)",
        "note": "",
    },
    {
        "color": "brown",
        "color_name": "brown",
        "hex": "#b2beb5",
        "R": 128,
        "G": 0,
        "B": 0,
        "RGB": "(128,0,0)",
        "note": "",
    },
    {
        "color": "brown",
        "color_name": "brown",
        "hex": "#f96",
        "R": 139,
        "G": 69,
        "B": 19,
        "RGB": "(139,69,19)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#007fff",
        "R": 0,
        "G": 139,
        "B": 139,
        "RGB": "(0,139,139)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#21abcd",
        "R": 60,
        "G": 179,
        "B": 113,
        "RGB": "(60,179,113)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#568203",
        "R": 0,
        "G": 255,
        "B": 255,
        "RGB": "(0,255,255)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#6e7f80",
        "R": 95,
        "G": 158,
        "B": 160,
        "RGB": "(95,158,160)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#7c0a02",
        "R": 175,
        "G": 238,
        "B": 238,
        "RGB": "(175,238,238)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#848482",
        "R": 176,
        "G": 224,
        "B": 230,
        "RGB": "(176,224,230)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#89cff0",
        "R": 224,
        "G": 255,
        "B": 255,
        "RGB": "(224,255,255)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#98777b",
        "R": 0,
        "G": 128,
        "B": 128,
        "RGB": "(0,128,128)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#a1caf1",
        "R": 32,
        "G": 178,
        "B": 170,
        "RGB": "(32,178,170)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#bcd4e6",
        "R": 64,
        "G": 224,
        "B": 208,
        "RGB": "(64,224,208)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#f0ffff",
        "R": 0,
        "G": 206,
        "B": 209,
        "RGB": "(0,206,209)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#f4c2c2",
        "R": 102,
        "G": 205,
        "B": 170,
        "RGB": "(102,205,170)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#fae7b5",
        "R": 0,
        "G": 250,
        "B": 154,
        "RGB": "(0,250,154)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#fdee00",
        "R": 127,
        "G": 255,
        "B": 212,
        "RGB": "(127,255,212)",
        "note": "",
    },
    {
        "color": "cyan",
        "color_name": "cyan",
        "hex": "#ffe135",
        "R": 72,
        "G": 209,
        "B": 204,
        "RGB": "(72,209,204)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#000",
        "R": 144,
        "G": 238,
        "B": 144,
        "RGB": "(144,238,144)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#00308f",
        "R": 0,
        "G": 255,
        "B": 127,
        "RGB": "(0,255,127)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#253529",
        "R": 50,
        "G": 205,
        "B": 50,
        "RGB": "(50,205,50)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#3b3c36",
        "R": 152,
        "G": 251,
        "B": 152,
        "RGB": "(152,251,152)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#3d0c02",
        "R": 0,
        "G": 255,
        "B": 0,
        "RGB": "(0,255,0)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#3d2b1f",
        "R": 0,
        "G": 128,
        "B": 0,
        "RGB": "(0,128,0)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#5d8aa8",
        "R": 46,
        "G": 139,
        "B": 87,
        "RGB": "(46,139,87)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#72a0c1",
        "R": 154,
        "G": 205,
        "B": 50,
        "RGB": "(154,205,50)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#9c2542",
        "R": 143,
        "G": 188,
        "B": 143,
        "RGB": "(143,188,143)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#9f8170",
        "R": 127,
        "G": 255,
        "B": 0,
        "RGB": "(127,255,0)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#a4c639",
        "R": 107,
        "G": 142,
        "B": 35,
        "RGB": "(107,142,35)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#bf4f51",
        "R": 124,
        "G": 252,
        "B": 0,
        "RGB": "(124,252,0)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#f5f5dc",
        "R": 0,
        "G": 100,
        "B": 0,
        "RGB": "(0,100,0)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#fe6f5e",
        "R": 173,
        "G": 255,
        "B": 47,
        "RGB": "(173,255,47)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#ff033e",
        "R": 85,
        "G": 107,
        "B": 47,
        "RGB": "(85,107,47)",
        "note": "",
    },
    {
        "color": "green",
        "color_name": "green",
        "hex": "#ffe4c4",
        "R": 34,
        "G": 139,
        "B": 34,
        "RGB": "(34,139,34)",
        "note": "",
    },
    {
        "color": "grey",
        "color_name": "grey",
        "hex": "#a32638",
        "R": 169,
        "G": 169,
        "B": 169,
        "RGB": "(169,169,169)",
        "note": "",
    },
    {
        "color": "grey",
        "color_name": "grey",
        "hex": "#c46210",
        "R": 128,
        "G": 128,
        "B": 128,
        "RGB": "(128,128,128)",
        "note": "",
    },
    {
        "color": "grey",
        "color_name": "grey",
        "hex": "#e32636",
        "R": 105,
        "G": 105,
        "B": 105,
        "RGB": "(105,105,105)",
        "note": "",
    },
    {
        "color": "grey",
        "color_name": "grey",
        "hex": "#e52b50",
        "R": 192,
        "G": 192,
        "B": 192,
        "RGB": "(192,192,192)",
        "note": "",
    },
    {
        "color": "grey",
        "color_name": "grey",
        "hex": "#efdecd",
        "R": 211,
        "G": 211,
        "B": 211,
        "RGB": "(211,211,211)",
        "note": "",
    },
    {
        "color": "grey",
        "color_name": "grey",
        "hex": "#f0f8ff",
        "R": 47,
        "G": 79,
        "B": 79,
        "RGB": "(47,79,79)",
        "note": "",
    },
    {
        "color": "grey",
        "color_name": "grey",
        "hex": "#ffbf00",
        "R": 112,
        "G": 128,
        "B": 144,
        "RGB": "(112,128,144)",
        "note": "",
    },
    {
        "color": "olive",
        "color_name": "olive",
        "hex": "#96c",
        "R": 128,
        "G": 128,
        "B": 0,
        "RGB": "(128,128,0)",
        "note": "",
    },
    {
        "color": "olive",
        "color_name": "olive",
        "hex": "#ff7e00",
        "R": 189,
        "G": 183,
        "B": 107,
        "RGB": "(189,183,107)",
        "note": "",
    },
    {
        "color": "orange",
        "color_name": "orange",
        "hex": "#008000",
        "R": 244,
        "G": 164,
        "B": 96,
        "RGB": "(244,164,96)",
        "note": "",
    },
    {
        "color": "orange",
        "color_name": "orange",
        "hex": "#841b2d",
        "R": 255,
        "G": 165,
        "B": 0,
        "RGB": "(255,165,0)",
        "note": "",
    },
    {
        "color": "orange",
        "color_name": "orange",
        "hex": "#8db600",
        "R": 255,
        "G": 99,
        "B": 71,
        "RGB": "(255,99,71)",
        "note": "",
    },
    {
        "color": "orange",
        "color_name": "orange",
        "hex": "#915c83",
        "R": 255,
        "G": 140,
        "B": 0,
        "RGB": "(255,140,0)",
        "note": "",
    },
    {
        "color": "orange",
        "color_name": "orange",
        "hex": "#cd9575",
        "R": 255,
        "G": 127,
        "B": 80,
        "RGB": "(255,127,80)",
        "note": "",
    },
    {
        "color": "orange",
        "color_name": "orange",
        "hex": "#f2f3f4",
        "R": 210,
        "G": 105,
        "B": 30,
        "RGB": "(210,105,30)",
        "note": "",
    },
    {
        "color": "orange",
        "color_name": "orange",
        "hex": "#faebd7",
        "R": 255,
        "G": 69,
        "B": 0,
        "RGB": "(255,69,0)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "",
        "R": 190,
        "G": 130,
        "B": 170,
        "RGB": "",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#0ff",
        "R": 255,
        "G": 0,
        "B": 255,
        "RGB": "(255,0,255)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#3b444b",
        "R": 255,
        "G": 182,
        "B": 193,
        "RGB": "(255,182,193)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#4b5320",
        "R": 240,
        "G": 128,
        "B": 128,
        "RGB": "(240,128,128)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#568203",
        "R": 221,
        "G": 160,
        "B": 221,
        "RGB": "(221,160,221)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#6e7f80",
        "R": 255,
        "G": 192,
        "B": 203,
        "RGB": "(255,192,203)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#7fffd4",
        "R": 255,
        "G": 105,
        "B": 180,
        "RGB": "(255,105,180)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#87a96b",
        "R": 255,
        "G": 228,
        "B": 225,
        "RGB": "(255,228,225)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#89cff0",
        "R": 238,
        "G": 130,
        "B": 238,
        "RGB": "(238,130,238)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#a52a2a",
        "R": 219,
        "G": 112,
        "B": 147,
        "RGB": "(219,112,147)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#b2beb5",
        "R": 199,
        "G": 21,
        "B": 133,
        "RGB": "(199,21,133)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#e9d66b",
        "R": 255,
        "G": 160,
        "B": 122,
        "RGB": "(255,160,122)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#f0ffff",
        "R": 250,
        "G": 128,
        "B": 114,
        "RGB": "(250,128,114)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#f96",
        "R": 218,
        "G": 112,
        "B": 214,
        "RGB": "(218,112,214)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#fbceb1",
        "R": 255,
        "G": 20,
        "B": 147,
        "RGB": "(255,20,147)",
        "note": "",
    },
    {
        "color": "pink",
        "color_name": "pink",
        "hex": "#fdee00",
        "R": 255,
        "G": 218,
        "B": 185,
        "RGB": "(255,218,185)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#21abcd",
        "R": 153,
        "G": 50,
        "B": 204,
        "RGB": "(153,50,204)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#7c0a02",
        "R": 75,
        "G": 0,
        "B": 130,
        "RGB": "(75,0,130)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#848482",
        "R": 230,
        "G": 230,
        "B": 250,
        "RGB": "(230,230,250)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#98777b",
        "R": 186,
        "G": 85,
        "B": 211,
        "RGB": "(186,85,211)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#9c2542",
        "R": 106,
        "G": 90,
        "B": 205,
        "RGB": "(106,90,205)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#9f8170",
        "R": 123,
        "G": 104,
        "B": 238,
        "RGB": "(123,104,238)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#a1caf1",
        "R": 138,
        "G": 43,
        "B": 226,
        "RGB": "(138,43,226)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#bcd4e6",
        "R": 147,
        "G": 112,
        "B": 219,
        "RGB": "(147,112,219)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#f4c2c2",
        "R": 139,
        "G": 0,
        "B": 139,
        "RGB": "(139,0,139)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#f5f5dc",
        "R": 128,
        "G": 0,
        "B": 128,
        "RGB": "(128,0,128)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#fae7b5",
        "R": 72,
        "G": 61,
        "B": 139,
        "RGB": "(72,61,139)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#ffe135",
        "R": 148,
        "G": 0,
        "B": 211,
        "RGB": "(148,0,211)",
        "note": "",
    },
    {
        "color": "purple",
        "color_name": "purple",
        "hex": "#ffe4c4",
        "R": 216,
        "G": 191,
        "B": 216,
        "RGB": "(216,191,216)",
        "note": "",
    },
    {
        "color": "red",
        "color_name": "red",
        "hex": "#000",
        "R": 233,
        "G": 150,
        "B": 122,
        "RGB": "(233,150,122)",
        "note": "",
    },
    {
        "color": "red",
        "color_name": "red",
        "hex": "#253529",
        "R": 205,
        "G": 92,
        "B": 92,
        "RGB": "(205,92,92)",
        "note": "",
    },
    {
        "color": "red",
        "color_name": "red",
        "hex": "#3b3c36",
        "R": 255,
        "G": 0,
        "B": 0,
        "RGB": "(255,0,0)",
        "note": "",
    },
    {
        "color": "red",
        "color_name": "red",
        "hex": "#3d0c02",
        "R": 178,
        "G": 34,
        "B": 34,
        "RGB": "(178,34,34)",
        "note": "",
    },
    {
        "color": "red",
        "color_name": "red",
        "hex": "#3d2b1f",
        "R": 165,
        "G": 42,
        "B": 42,
        "RGB": "(165,42,42)",
        "note": "",
    },
    {
        "color": "red",
        "color_name": "red",
        "hex": "#bf4f51",
        "R": 139,
        "G": 0,
        "B": 0,
        "RGB": "(139,0,0)",
        "note": "",
    },
    {
        "color": "red",
        "color_name": "red",
        "hex": "#fe6f5e",
        "R": 220,
        "G": 20,
        "B": 60,
        "RGB": "(220,20,60)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#00308f",
        "R": 240,
        "G": 255,
        "B": 255,
        "RGB": "(240,255,255)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#5d8aa8",
        "R": 250,
        "G": 235,
        "B": 215,
        "RGB": "(250,235,215)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#72a0c1",
        "R": 255,
        "G": 250,
        "B": 240,
        "RGB": "(255,250,240)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#96c",
        "R": 255,
        "G": 250,
        "B": 250,
        "RGB": "(255,250,250)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#a32638",
        "R": 220,
        "G": 220,
        "B": 220,
        "RGB": "(220,220,220)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#a4c639",
        "R": 255,
        "G": 255,
        "B": 255,
        "RGB": "(255,255,255)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#c46210",
        "R": 255,
        "G": 255,
        "B": 240,
        "RGB": "(255,255,240)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#e32636",
        "R": 240,
        "G": 255,
        "B": 240,
        "RGB": "(240,255,240)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#e52b50",
        "R": 250,
        "G": 240,
        "B": 230,
        "RGB": "(250,240,230)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#efdecd",
        "R": 255,
        "G": 240,
        "B": 245,
        "RGB": "(255,240,245)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#f0f8ff",
        "R": 248,
        "G": 248,
        "B": 255,
        "RGB": "(248,248,255)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#f2f3f4",
        "R": 245,
        "G": 245,
        "B": 245,
        "RGB": "(245,245,245)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#ff033e",
        "R": 255,
        "G": 245,
        "B": 238,
        "RGB": "(255,245,238)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#ff7e00",
        "R": 253,
        "G": 245,
        "B": 230,
        "RGB": "(253,245,230)",
        "note": "",
    },
    {
        "color": "white",
        "color_name": "white",
        "hex": "#ffbf00",
        "R": 245,
        "G": 255,
        "B": 250,
        "RGB": "(245,255,250)",
        "note": "",
    },
    {
        "color": "yellow",
        "color_name": "yellow",
        "hex": "#008000",
        "R": 250,
        "G": 250,
        "B": 210,
        "RGB": "(250,250,210)",
        "note": "",
    },
    {
        "color": "yellow",
        "color_name": "yellow",
        "hex": "#0ff",
        "R": 255,
        "G": 255,
        "B": 0,
        "RGB": "(255,255,0)",
        "note": "",
    },
    {
        "color": "yellow",
        "color_name": "yellow",
        "hex": "#841b2d",
        "R": 240,
        "G": 230,
        "B": 140,
        "RGB": "(240,230,140)",
        "note": "",
    },
    {
        "color": "yellow",
        "color_name": "yellow",
        "hex": "#8db600",
        "R": 255,
        "G": 255,
        "B": 224,
        "RGB": "(255,255,224)",
        "note": "",
    },
    {
        "color": "yellow",
        "color_name": "yellow",
        "hex": "#915c83",
        "R": 218,
        "G": 165,
        "B": 32,
        "RGB": "(218,165,32)",
        "note": "",
    },
    {
        "color": "yellow",
        "color_name": "yellow",
        "hex": "#cd9575",
        "R": 255,
        "G": 215,
        "B": 0,
        "RGB": "(255,215,0)",
        "note": "",
    },
    {
        "color": "yellow",
        "color_name": "yellow",
        "hex": "#faebd7",
        "R": 255,
        "G": 250,
        "B": 205,
        "RGB": "(255,250,205)",
        "note": "",
    },
    {
        "color": "yellow",
        "color_name": "yellow",
        "hex": "#fbceb1",
        "R": 238,
        "G": 232,
        "B": 170,
        "RGB": "(238,232,170)",
        "note": "",
    },
]


EFT_IDS = {
    "orange": {
        "wikidata_concept": "Q39338",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q39338",
        "europeana_id": "10411",
    },
    "black": {
        "wikidata_concept": "Q23445",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q23445",
        "europeana_id": "10401",
    },
    "purple": {
        "wikidata_concept": "Q3257809",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q3257809",
        "europeana_id": "10413",
    },
    "red": {
        "wikidata_concept": "Q3142",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q3142",
        "europeana_id": "10414",
    },
    "grey": {
        "wikidata_concept": "Q42519",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q42519",
        "europeana_id": "10405",
    },
    "gold": {
        "wikidata_concept": "Q208045",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q208045",
        "europeana_id": "10406",
    },
    "copper": {
        "wikidata_concept": "Q2722041",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q2722041",
        "europeana_id": "10409",
    },
    "yellow": {
        "wikidata_concept": "Q943",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q943",
        "europeana_id": "10417",
    },
    "green": {
        "wikidata_concept": "Q3133",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q3133",
        "europeana_id": "10404",
    },
    "brown": {
        "wikidata_concept": "Q47071",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q47071",
        "europeana_id": "10403",
    },
    "blue": {
        "wikidata_concept": "Q1088",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q1088",
        "europeana_id": "10402",
    },
    "white": {
        "wikidata_concept": "Q23444",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q23444",
        "europeana_id": "10416",
    },
    "beige": {
        "wikidata_concept": "Q843607",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q843607",
        "europeana_id": "10778",
    },
    "pink": {
        "wikidata_concept": "Q429220",
        "wikidata_concepturi": "http://www.wikidata.org/entity/Q429220",
        "europeana_id": "10412",
    },
}
